# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 16
#
# Initialize kernel
/target/setDistance 5 mm #HAS TO GO HERE
/run/eventModulo 0 1
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0#

# 
/target/setDistance 1 m
# gamma 6 MeV to the direction (0.,0.,1.)
#

/gun/particle proton
/gun/energy 2.6 MeV
/gun/position 0 0 -20 cm
#
/run/beamOn 10
